# Generated by Django 4.2.18 on 2025-01-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pintura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.IntegerField()),
                ('autor', models.CharField(max_length=30)),
                ('tecnicaUsada', models.CharField(max_length=20)),
                ('fechaSubida', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('imagen', models.FileField(upload_to='')),
            ],
        ),
    ]
